/**
 * Generated by Bobkit. Do not edit by hand.
 * Registers Bobkit skills and injects the using-bobkit bootstrap once.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function stripFrontmatter(content) {
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  return match ? content.slice(match[0].length) : content;
}

export const BobkitPlugin = async () => {
  const skillsDir = path.resolve(__dirname, '../../skills');

  function bootstrapContent() {
    const skillPath = path.join(skillsDir, 'using-bobkit', 'SKILL.md');
    if (!fs.existsSync(skillPath)) {
      return null;
    }

    const content = stripFrontmatter(fs.readFileSync(skillPath, 'utf8'));
    return `<BOBKIT_BOOTSTRAP>
You have Bobkit, a portable workflow kit for AI coding agents.
The using-bobkit skill content is already loaded. Follow it before planning, coding, debugging, reviewing, or verifying work.

${content}
</BOBKIT_BOOTSTRAP>`;
  }

  return {
    config: async (config) => {
      config.skills = config.skills || {};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir);
      }
    },

    'experimental.chat.messages.transform': async (_input, output) => {
      if (!output.messages || output.messages.length === 0) {
        return;
      }

      const bootstrap = bootstrapContent();
      if (!bootstrap) {
        return;
      }

      const firstUser = output.messages.find((message) => message.info && message.info.role === 'user');
      if (!firstUser || !firstUser.parts || firstUser.parts.length === 0) {
        return;
      }

      if (firstUser.parts.some((part) => part.type === 'text' && part.text.includes('<BOBKIT_BOOTSTRAP>'))) {
        return;
      }

      firstUser.parts.unshift({ ...firstUser.parts[0], type: 'text', text: bootstrap });
    }
  };
};
