#!/usr/bin/env node

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs';
import path from 'node:path';

const REQUIRED_TOP_LEVEL_DIRS = [
  'skills',
  'workflows',
  'agents',
  'guardrails',
  'templates',
  'adapters',
  'evals',
  'scripts',
  'docs',
  'packs'
];

const REQUIRED_EVAL_SUITES = [
  'skill-activation',
  'workflow-compliance',
  'guardrails',
  'provider-smoke'
];

const REQUIRED_EVAL_PROMPTS = [
  'skill-activation.txt',
  'workflow-compliance.txt',
  'guardrail-check.txt'
];

const GENERATED_HEADER = 'Generated by Bobkit. Do not edit by hand.';

function usage() {
  return `Bobkit V0 CLI

Usage:
  node scripts/bobkit.mjs validate
  node scripts/bobkit.mjs compile --target all
  node scripts/bobkit.mjs compile --target claude|codex|gemini|opencode|cursor|copilot
`;
}

function findRoot(startDir) {
  let current = path.resolve(startDir);

  while (true) {
    if (existsSync(path.join(current, 'bobkit.json'))) {
      return current;
    }

    const parent = path.dirname(current);
    if (parent === current) {
      throw new Error('Could not find bobkit.json. Run this command inside the Bobkit repository.');
    }
    current = parent;
  }
}

function readJson(root, relPath) {
  const fullPath = path.join(root, relPath);
  try {
    return JSON.parse(readFileSync(fullPath, 'utf8'));
  } catch (error) {
    throw new Error(`Invalid JSON in ${relPath}: ${error.message}`);
  }
}

function writeText(root, relPath, content) {
  const fullPath = path.join(root, relPath);
  mkdirSync(path.dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content.endsWith('\n') ? content : `${content}\n`);
}

function writeJson(root, relPath, value) {
  writeText(root, relPath, JSON.stringify(value, null, 2));
}

function requireField(object, field, label, errors) {
  if (object[field] === undefined || object[field] === null || object[field] === '') {
    errors.push(`${label} is missing required field "${field}"`);
  }
}

function walkFiles(root, relDir = '.') {
  const absDir = path.join(root, relDir);
  if (!existsSync(absDir)) {
    return [];
  }

  const ignored = new Set(['.git', 'node_modules', '.cache', 'dist']);
  const files = [];

  for (const entry of readdirSync(absDir)) {
    if (ignored.has(entry)) {
      continue;
    }

    const relPath = path.join(relDir, entry);
    const absPath = path.join(root, relPath);
    const stat = statSync(absPath);

    if (stat.isDirectory()) {
      files.push(...walkFiles(root, relPath));
    } else if (stat.isFile()) {
      files.push(relPath);
    }
  }

  return files.sort();
}

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) {
    return { frontmatter: null, body: content };
  }

  const frontmatter = {};
  for (const rawLine of match[1].split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const index = line.indexOf(':');
    if (index === -1) {
      continue;
    }

    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim().replace(/^['"]|['"]$/g, '');
    frontmatter[key] = value;
  }

  return { frontmatter, body: content.slice(match[0].length) };
}

function validateSkill(root, skillsDir, skillName, seenNames, errors) {
  const relSkillPath = path.join(skillsDir, skillName, 'SKILL.md');
  const absSkillPath = path.join(root, relSkillPath);

  if (!existsSync(absSkillPath)) {
    errors.push(`Missing skill file: ${relSkillPath}`);
    return;
  }

  const { frontmatter } = parseFrontmatter(readFileSync(absSkillPath, 'utf8'));
  if (!frontmatter) {
    errors.push(`${relSkillPath} is missing YAML frontmatter`);
    return;
  }

  requireField(frontmatter, 'name', relSkillPath, errors);
  requireField(frontmatter, 'description', relSkillPath, errors);

  if (frontmatter.name && frontmatter.name !== skillName) {
    errors.push(`${relSkillPath} frontmatter name "${frontmatter.name}" must match directory "${skillName}"`);
  }

  if (frontmatter.name) {
    if (seenNames.has(frontmatter.name)) {
      errors.push(`Duplicate skill name: ${frontmatter.name}`);
    }
    seenNames.add(frontmatter.name);
  }
}

function validateSkills(root, config, errors) {
  const skillsDir = config.skillsDir;
  const absSkillsDir = path.join(root, skillsDir);

  if (!existsSync(absSkillsDir)) {
    errors.push(`Missing skills directory: ${skillsDir}`);
    return;
  }

  const seenNames = new Set();
  const skillDirs = readdirSync(absSkillsDir)
    .filter((entry) => statSync(path.join(absSkillsDir, entry)).isDirectory())
    .sort();

  for (const requiredSkill of config.requiredSkills || []) {
    if (!skillDirs.includes(requiredSkill)) {
      errors.push(`Missing required skill directory: ${path.join(skillsDir, requiredSkill)}`);
    }
  }

  for (const skillName of skillDirs) {
    validateSkill(root, skillsDir, skillName, seenNames, errors);
  }
}

function validateAdapters(root, config, errors) {
  const seen = new Set();

  if (!Array.isArray(config.adapters) || config.adapters.length === 0) {
    errors.push('bobkit.json adapters must be a non-empty array');
    return;
  }

  for (const adapter of config.adapters) {
    requireField(adapter, 'id', 'bobkit.json adapter entry', errors);
    requireField(adapter, 'displayName', `adapter ${adapter.id || '<unknown>'}`, errors);
    requireField(adapter, 'supportLevel', `adapter ${adapter.id || '<unknown>'}`, errors);

    if (!Array.isArray(adapter.outputPaths) || adapter.outputPaths.length === 0) {
      errors.push(`adapter ${adapter.id || '<unknown>'} must list outputPaths`);
    }

    if (adapter.id) {
      if (seen.has(adapter.id)) {
        errors.push(`Duplicate adapter id: ${adapter.id}`);
      }
      seen.add(adapter.id);
    }

    const relManifest = path.join('adapters', adapter.id || '', 'adapter.json');
    if (!existsSync(path.join(root, relManifest))) {
      errors.push(`Missing adapter manifest: ${relManifest}`);
      continue;
    }

    const manifest = readJson(root, relManifest);
    if (manifest.id !== adapter.id) {
      errors.push(`${relManifest} id "${manifest.id}" must match bobkit.json id "${adapter.id}"`);
    }

    if (!Array.isArray(manifest.outputs) || manifest.outputs.length === 0) {
      errors.push(`${relManifest} must list outputs`);
    }

    for (const outputPath of adapter.outputPaths || []) {
      if (!existsSync(path.join(root, outputPath))) {
        errors.push(`Missing generated provider output for ${adapter.id}: ${outputPath}`);
      }
    }
  }
}

function validateEvalSkeleton(root, errors) {
  const promptfooConfig = 'evals/promptfooconfig.yaml';
  if (!existsSync(path.join(root, promptfooConfig))) {
    errors.push(`Missing ${promptfooConfig}`);
  }

  for (const suite of REQUIRED_EVAL_SUITES) {
    const relPath = `evals/suites/${suite}.yaml`;
    if (!existsSync(path.join(root, relPath))) {
      errors.push(`Missing eval suite: ${relPath}`);
    }
  }

  for (const prompt of REQUIRED_EVAL_PROMPTS) {
    const relPath = `evals/fixtures/prompts/${prompt}`;
    if (!existsSync(path.join(root, relPath))) {
      errors.push(`Missing eval prompt fixture: ${relPath}`);
    }
  }
}

function validateReferences(root, errors) {
  for (const relPath of walkFiles(root)) {
    const ext = path.extname(relPath);
    const content = readFileSync(path.join(root, relPath), 'utf8');

    if (ext === '.md' || ext === '.mdc') {
      const linkPattern = /\[[^\]]+\]\(([^)]+)\)/g;
      for (const match of content.matchAll(linkPattern)) {
        const rawTarget = match[1].trim();
        if (
          !rawTarget ||
          rawTarget.startsWith('#') ||
          rawTarget.startsWith('http://') ||
          rawTarget.startsWith('https://') ||
          rawTarget.startsWith('mailto:')
        ) {
          continue;
        }

        const withoutAnchor = rawTarget.split('#')[0];
        const targetPath = path.resolve(path.dirname(path.join(root, relPath)), withoutAnchor);
        if (!targetPath.startsWith(root) || !existsSync(targetPath)) {
          errors.push(`${relPath} has broken local link: ${rawTarget}`);
        }
      }
    }

    if (ext === '.yaml' || ext === '.yml') {
      const fileRefPattern = /file:\/\/([^\s'"]+)/g;
      for (const match of content.matchAll(fileRefPattern)) {
        const rawTarget = match[1].trim();
        const targetPath = path.join(root, rawTarget);
        if (!existsSync(targetPath)) {
          errors.push(`${relPath} has broken file:// reference: ${rawTarget}`);
        }
      }
    }
  }
}

function validate(root) {
  const errors = [];

  for (const relDir of REQUIRED_TOP_LEVEL_DIRS) {
    if (!existsSync(path.join(root, relDir))) {
      errors.push(`Missing top-level directory: ${relDir}`);
    }
  }

  const config = readJson(root, 'bobkit.json');
  for (const field of ['id', 'name', 'version', 'description', 'skillsDir', 'workflowsDir', 'agentsDir', 'templatesDir']) {
    requireField(config, field, 'bobkit.json', errors);
  }

  validateSkills(root, config, errors);
  validateAdapters(root, config, errors);
  validateEvalSkeleton(root, errors);
  validateReferences(root, errors);

  if (errors.length > 0) {
    console.error('Bobkit validation failed:');
    for (const error of errors) {
      console.error(`  - ${error}`);
    }
    process.exitCode = 1;
    return;
  }

  console.log('Bobkit validation passed.');
}

function adapterById(config, id) {
  return config.adapters.find((adapter) => adapter.id === id);
}

function commonKeywords() {
  return [
    'ai-coding-agents',
    'workflow',
    'skills',
    'planning',
    'verification',
    'guardrails'
  ];
}

function compileClaude(root, config) {
  writeJson(root, '.claude-plugin/plugin.json', {
    name: config.id,
    version: config.version,
    description: config.description,
    author: {
      name: 'Bobkit contributors'
    },
    homepage: 'https://github.com/BobvD/bobkit',
    repository: 'https://github.com/BobvD/bobkit',
    license: 'MIT',
    keywords: commonKeywords(),
    skills: './skills/',
    agents: './agents/'
  });
}

function compileCodex(root, config) {
  writeJson(root, '.codex-plugin/plugin.json', {
    name: config.id,
    version: config.version,
    description: config.description,
    author: {
      name: 'Bobkit contributors',
      url: 'https://github.com/BobvD'
    },
    homepage: 'https://github.com/BobvD/bobkit',
    repository: 'https://github.com/BobvD/bobkit',
    license: 'MIT',
    keywords: commonKeywords(),
    skills: './skills/',
    interface: {
      displayName: config.name,
      shortDescription: 'Portable workflows for AI coding agents',
      longDescription: 'Use Bobkit to guide AI coding agents through spec-first planning, safe implementation, code review, guardrails, and verification gates.',
      developerName: 'Bobkit contributors',
      category: 'Coding',
      capabilities: ['Interactive', 'Read', 'Write'],
      defaultPrompt: [
        'Use Bobkit to plan this feature before implementation.',
        'Use Bobkit to verify this change before completion.'
      ],
      brandColor: '#0F766E',
      screenshots: []
    }
  });
}

function compileGemini(root, config) {
  writeJson(root, 'gemini-extension.json', {
    name: config.id,
    description: config.description,
    version: config.version
  });
}

function compileOpenCode(root, config) {
  const plugin = `/**
 * ${GENERATED_HEADER}
 * Registers Bobkit skills and injects the using-bobkit bootstrap once.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function stripFrontmatter(content) {
  const match = content.match(/^---\\r?\\n[\\s\\S]*?\\r?\\n---\\r?\\n?/);
  return match ? content.slice(match[0].length) : content;
}

export const BobkitPlugin = async () => {
  const skillsDir = path.resolve(__dirname, '../../skills');

  function bootstrapContent() {
    const skillPath = path.join(skillsDir, 'using-bobkit', 'SKILL.md');
    if (!fs.existsSync(skillPath)) {
      return null;
    }

    const content = stripFrontmatter(fs.readFileSync(skillPath, 'utf8'));
    return \`<BOBKIT_BOOTSTRAP>
You have Bobkit, a portable workflow kit for AI coding agents.
The using-bobkit skill content is already loaded. Follow it before planning, coding, debugging, reviewing, or verifying work.

\${content}
</BOBKIT_BOOTSTRAP>\`;
  }

  return {
    config: async (config) => {
      config.skills = config.skills || {};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir);
      }
    },

    'experimental.chat.messages.transform': async (_input, output) => {
      if (!output.messages || output.messages.length === 0) {
        return;
      }

      const bootstrap = bootstrapContent();
      if (!bootstrap) {
        return;
      }

      const firstUser = output.messages.find((message) => message.info && message.info.role === 'user');
      if (!firstUser || !firstUser.parts || firstUser.parts.length === 0) {
        return;
      }

      if (firstUser.parts.some((part) => part.type === 'text' && part.text.includes('<BOBKIT_BOOTSTRAP>'))) {
        return;
      }

      firstUser.parts.unshift({ ...firstUser.parts[0], type: 'text', text: bootstrap });
    }
  };
};
`;

  writeText(root, '.opencode/plugins/bobkit.js', plugin);
}

function compileCursor(root, config) {
  const rule = `---
description: Bobkit portable workflow discipline for planning, implementation, debugging, review, and verification.
globs: "**/*"
alwaysApply: true
---

# ${config.name}

You are working in a repository that uses Bobkit.

Before coding, debugging, reviewing, or declaring completion:

1. Read and follow the relevant Bobkit skill from \`skills/\`.
2. Start with \`skills/using-bobkit/SKILL.md\` when unsure.
3. Use spec-first planning for new features.
4. Use systematic debugging for failures.
5. Use the verification gate before completion.

Do not treat this rule as a replacement for project instructions. Project and user instructions remain higher priority.
`;

  const planCommand = `---
description: Start a Bobkit spec-first planning pass
---

Use Bobkit to plan the requested work before implementation.

1. Load \`skills/using-bobkit/SKILL.md\`.
2. Load \`skills/spec-first-development/SKILL.md\`.
3. Produce a concise spec and implementation plan using \`templates/spec.md\` and \`templates/plan.md\`.
4. Do not edit implementation files until the plan is approved.
`;

  const verifyCommand = `---
description: Run a Bobkit verification gate
---

Use Bobkit to verify the current work.

1. Load \`skills/verification-gate/SKILL.md\`.
2. Inspect the diff and requested scope.
3. Run the focused verification commands that apply.
4. Report exact commands, results, evidence, and deferred checks.
`;

  writeText(root, '.cursor/rules/bobkit.mdc', rule);
  writeText(root, '.cursor/commands/bobkit-plan.md', planCommand);
  writeText(root, '.cursor/commands/bobkit-verify.md', verifyCommand);
}

function compileCopilot(root, config) {
  const instructions = `# Bobkit Instructions

${GENERATED_HEADER}

This repository uses Bobkit, a portable workflow kit for AI coding agents.

## Working Rules

- Before planning, coding, debugging, reviewing, or declaring completion, check the relevant Bobkit skill.
- Start with \`skills/using-bobkit/SKILL.md\` when unsure.
- Use spec-first planning for new features and meaningful behavior changes.
- Use systematic debugging for failures.
- Use the verification gate before claiming work is complete.
- Project and user instructions remain higher priority than Bobkit.

## Skills

Project skills are mirrored into \`.github/skills/\` for GitHub Copilot. Use them when the task matches their descriptions.
`;

  writeText(root, '.github/copilot-instructions.md', instructions);
  copySkills(root, config.skillsDir, '.github/skills');
}

function copySkills(root, sourceDir, destDir) {
  const absSourceDir = path.join(root, sourceDir);
  const absDestDir = path.join(root, destDir);

  mkdirSync(absDestDir, { recursive: true });

  for (const skillName of readdirSync(absSourceDir).sort()) {
    const absSkillDir = path.join(absSourceDir, skillName);
    if (!statSync(absSkillDir).isDirectory()) {
      continue;
    }

    const sourceSkill = path.join(absSkillDir, 'SKILL.md');
    if (!existsSync(sourceSkill)) {
      continue;
    }

    const destSkillDir = path.join(absDestDir, skillName);
    mkdirSync(destSkillDir, { recursive: true });
    copyFileSync(sourceSkill, path.join(destSkillDir, 'SKILL.md'));
  }
}

function compileTarget(root, config, target) {
  switch (target) {
    case 'claude':
      compileClaude(root, config);
      break;
    case 'codex':
      compileCodex(root, config);
      break;
    case 'gemini':
      compileGemini(root, config);
      break;
    case 'opencode':
      compileOpenCode(root, config);
      break;
    case 'cursor':
      compileCursor(root, config);
      break;
    case 'copilot':
      compileCopilot(root, config);
      break;
    default:
      throw new Error(`Unknown compile target: ${target}`);
  }
}

function parseTarget(args) {
  const targetFlagIndex = args.indexOf('--target');
  if (targetFlagIndex !== -1) {
    return args[targetFlagIndex + 1] || 'all';
  }

  const inlineTarget = args.find((arg) => arg.startsWith('--target='));
  if (inlineTarget) {
    return inlineTarget.slice('--target='.length) || 'all';
  }

  return 'all';
}

function cleanTargetOutput(root, target) {
  if (target === 'copilot') {
    rmSync(path.join(root, '.github', 'skills'), { recursive: true, force: true });
  }
}

function compile(root, args) {
  const config = readJson(root, 'bobkit.json');
  const target = parseTarget(args);
  const validTargets = config.adapters.map((adapter) => adapter.id).sort();
  const targets = target === 'all' ? validTargets : [target];

  for (const requested of targets) {
    if (!adapterById(config, requested)) {
      throw new Error(`Unsupported target "${requested}". Expected one of: all, ${validTargets.join(', ')}`);
    }
  }

  for (const requested of targets) {
    cleanTargetOutput(root, requested);
    compileTarget(root, config, requested);
    console.log(`Compiled ${requested}`);
  }
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === '--help' || command === '-h') {
    console.log(usage());
    return;
  }

  const root = findRoot(process.cwd());

  try {
    if (command === 'validate') {
      validate(root);
      return;
    }

    if (command === 'compile') {
      compile(root, args.slice(1));
      return;
    }

    console.error(usage());
    process.exitCode = 1;
  } catch (error) {
    console.error(`Bobkit ${command} failed: ${error.message}`);
    process.exitCode = 1;
  }
}

main();
